// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class I32Array2 extends NonGrowableListView<int> {
  static const arraySize = 2;

  @internal
  Int32List get inner => _inner;
  final Int32List _inner;

  I32Array2(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  I32Array2.init() : this(Int32List(arraySize));
}
