// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SMTCConfig {
  final bool playEnabled;
  final bool pauseEnabled;
  final bool stopEnabled;
  final bool nextEnabled;
  final bool prevEnabled;
  final bool fastForwardEnabled;
  final bool rewindEnabled;

  const SMTCConfig({
    required this.playEnabled,
    required this.pauseEnabled,
    required this.stopEnabled,
    required this.nextEnabled,
    required this.prevEnabled,
    required this.fastForwardEnabled,
    required this.rewindEnabled,
  });

  @override
  int get hashCode =>
      playEnabled.hashCode ^
      pauseEnabled.hashCode ^
      stopEnabled.hashCode ^
      nextEnabled.hashCode ^
      prevEnabled.hashCode ^
      fastForwardEnabled.hashCode ^
      rewindEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SMTCConfig &&
          runtimeType == other.runtimeType &&
          playEnabled == other.playEnabled &&
          pauseEnabled == other.pauseEnabled &&
          stopEnabled == other.stopEnabled &&
          nextEnabled == other.nextEnabled &&
          prevEnabled == other.prevEnabled &&
          fastForwardEnabled == other.fastForwardEnabled &&
          rewindEnabled == other.rewindEnabled;
}
