// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PlaybackTimeline {
  final PlatformInt64 startTimeMs;
  final PlatformInt64 endTimeMs;
  final PlatformInt64 positionMs;
  final PlatformInt64? minSeekTimeMs;
  final PlatformInt64? maxSeekTimeMs;

  const PlaybackTimeline({
    required this.startTimeMs,
    required this.endTimeMs,
    required this.positionMs,
    this.minSeekTimeMs,
    this.maxSeekTimeMs,
  });

  @override
  int get hashCode =>
      startTimeMs.hashCode ^
      endTimeMs.hashCode ^
      positionMs.hashCode ^
      minSeekTimeMs.hashCode ^
      maxSeekTimeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackTimeline &&
          runtimeType == other.runtimeType &&
          startTimeMs == other.startTimeMs &&
          endTimeMs == other.endTimeMs &&
          positionMs == other.positionMs &&
          minSeekTimeMs == other.minSeekTimeMs &&
          maxSeekTimeMs == other.maxSeekTimeMs;
}
