[package]
name = "metadata_god"
version = "0.5.3"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.89"
flutter_rust_bridge = "=2.5.0"
lofty = "0.20.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
