[package]
name = 'flutter_discord_rpc'
version = '0.1.0+1'
edition = '2021'

[lib]
crate-type = ['staticlib', 'cdylib']

[[bin]]
name = 'main'
path = 'src/main.rs'

[build-dependencies]
flutter_rust_bridge_codegen = '1.82.*'

[dependencies]
anyhow = '1.0.82'
discord-rich-presence = { git = "https://github.com/soumyaDghosh/discord-rich-presence", branch = "snap-fix"}
flutter_rust_bridge = '1.82.*'
lazy_static = '1.4.0'
